#!/usr/bin/env python3
import pathlib
import re

ROOT = pathlib.Path(".")

# ============================================================
# 正则：自动生成的 Phytium 私有头（❗只用于识别 / 跳过）
# ============================================================
AUTO_GENERATED_HEADER = re.compile(
    r"/\*{3,}.*?"
    r"Phytium\s+Corp.*?"
    r"automatically\s+generated.*?"
    r"Any\s+changes\s+made\s+to\s+this\s+file\s+are\s+lost.*?"
    r"\*{3,}/",
    re.IGNORECASE | re.DOTALL,
)

# ============================================================
# 需要真正替换的规则
# ============================================================
RULES = [

    # --------------------------------------------------------
    # 1) Phytium proprietary header (2004–2016, 前半段) → Apache-2.0
    # --------------------------------------------------------
    (
        re.compile(
            r"/\*{3,}\s*\*{2}.*?"
            r"Copyright\s*\(c\)\s*2004\s*-\s*2016\s*by\s*Phytium\s+Corp\..*?"
            r"confidential.*?"
            r"written\s+permission\s+of\s+Phytium\s+Corporation\..*?"
            r"\*{2}\s*$",
            re.IGNORECASE | re.DOTALL | re.MULTILINE,
        ),
        """/*******************************************************************************
**                                                                            **
** Copyright (c) 2025 Phytium Technology Co., Ltd.
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
**                                                                            **""",
    ),

    # --------------------------------------------------------
    # 2) Phytium proprietary header（2025，整块）→ Apache-2.0
    # --------------------------------------------------------
    (
        re.compile(
            r"/\*{10,}\s*\*.*?"
            r"Copyright\s*\(c\)\s*2025.*Phytium\s+Technology\s+Co\.,\s+Ltd\..*?"
            r"confidential.*?"
            r"Phytium\s+Corporation.*?"
            r"\*{10,}/",
            re.IGNORECASE | re.DOTALL,
        ),
        """/****************************************************************************
*
* Copyright (c) 2025 Phytium Technology Co., Ltd.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*****************************************************************************/""",
    ),

    # --------------------------------------------------------
    # 3) ftg340 / ftg340 → ftg340
    # --------------------------------------------------------
    (
        re.compile(r"\bgalcore\b", re.IGNORECASE),
        "ftg340",
    ),
]


def is_text_file(path: pathlib.Path) -> bool:
    try:
        return b"\0" not in path.read_bytes()
    except Exception:
        return False


def process_file(path: pathlib.Path):
    try:
        text = path.read_text(errors="ignore")
    except Exception:
        return

    # --------------------------------------------------------
    # 🚫 自动生成文件：直接跳过
    # --------------------------------------------------------
    if AUTO_GENERATED_HEADER.search(text):
        print(f"↷ skip autogenerated: {path}")
        return

    original = text
    for pattern, repl in RULES:
        text = pattern.sub(repl, text)

    if text != original:
        path.write_text(text)
        print(f"✔ modified: {path}")


def main():
    for p in ROOT.rglob("*"):
        if p.is_file() and is_text_file(p):
            process_file(p)


if __name__ == "__main__":
    main()

